# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='is_important',
            field=models.BooleanField(default=True),
        ),
    ]
