# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='is_threatened',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
