# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_tree_is_threatened'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avg_rain', models.FloatField(blank=True, null=True)),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tree',
            name='is_threatened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.TreeSpecies'),
        ),
        migrations.AddField(
            model_name='tree',
            name='environment',
            field=models.ManyToManyField(to='trees.Environment'),
        ),
    ]
