# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_auto_20170419_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='environment',
        ),
    ]
