# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='code',
            field=models.IntegerField(default=0, verbose_name='Codigo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discipline',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default=0, max_length=50, verbose_name='Funcao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
