# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20170517_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_letter', models.CharField(max_length=2, verbose_name='Turma')),
                ('class_time', models.TimeField(verbose_name='Horario')),
            ],
        ),
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='discipline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Discipline'),
        ),
    ]
