# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20170517_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Professor'), (2, 'Monitor')]),
        ),
    ]
